version: 0.2

env:
  variables:
    S3_BUCKET: madebyraf.tech-resumewebsite
    CLOUDFRONT_DISTRIBUTION_ID: E2TSQIE9BDWTRX

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ "s3://$S3_BUCKET" --delete
      - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"

artifacts:
  files:
    - '**/*'
  discard-paths: yes

