version: 0.2

env:
  variables:
    S3_BUCKET: madebyraf.tech-resumewebsite
    CLOUDFRONT_DISTRIBUTION_ID: E2TSQIE9BDWTRX

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      # Sync all files (adds/removes as needed)
      - aws s3 sync dist/ "s3://$S3_BUCKET" --delete
      # Ensure HTML has a short cache (fast deploys)
      - aws s3 cp dist/index.html "s3://$S3_BUCKET/index.html" --cache-control "public, max-age=300" --content-type "text/html"
      # Give hashed assets a long cache (cheap & fast)
      - aws s3 cp dist/assets/ "s3://$S3_BUCKET/assets/" --recursive --cache-control "public, max-age=31536000, immutable"
      - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"

artifacts:
  files:
    - '**/*'
  discard-paths: yes

